INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (1, 'Blanca', 44, 8, 15, 4.6);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (2, 'Mona', 12, 8, 20, 3.9);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (3, 'Mulata', 1, 8, 27, 5.2);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (4, 'Mestiza', 4, 8, 29, 4.8);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (5, 'Negra', 42, 8, 25, 6.4);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (6, 'Rose', 35, 8, 15, 3.8);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (7, 'Blonde', 12, 7, 19, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (8, 'Witbier', 45, 7, 16, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (9, 'Pale Ale', 31, 7, 30, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (10, 'Porter', 34, 7, 30, 5.5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (11, 'IPA', 26, 7, 60, 6);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (12, 'Saison', 36, 7, 27, 6);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (13, 'Açaí', 27, 9, 0, 6.7);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (14, 'Cacao', 27, 9, 0, 6.2);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (15, 'Canábica', 27, 9, 0, 6.7);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (16, 'Colorada', 27, 9, 0, 5.5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (17, 'Coca', 4, 9, 0, 6.2);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (18, 'Gringa', 4, 9, 0, 6.3);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (19, 'IPA Maracuyá', 26, 11, 45, 6.5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (20, 'Barley Wine', 13, 11, 45, 12);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (21, 'Dog Lover', 43, 11, 32, 4.5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (22, 'Café', 37, 11, 30, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (23, 'Pueblito', 32, 11, 25, 4.5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (24, 'Maracuyá', 7, 11, 23, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (25, 'Roja', 43, 11, 32, 4.5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (26, 'Chocolate', 15, 11, 38, 8.5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (27, 'Rubia', 32, 11, 25, 4.5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (28, 'Imperial Strout', 25, 11, 40, 8.5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (29, 'Septimazo', 26, 2, 83, 6);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (30, 'Macondo', 40, 2, 37, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (31, 'Monserrate', 11, 2, 37, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (32, 'Lager', 29, 2, 18, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (33, 'Bacatá', 45, 2, 14, 4.1);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (34, 'Chapinero', 34, 2, 35, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (35, 'Cajicá', 24, 2, 16, 5.3);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (36, 'Isabel la Católica', 12, 1, 0, 4.8);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (37, 'Dulcinea', 14, 1, 0, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (38, 'Juana de Arco', 34, 1, 0, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (39, 'Maria Antonieta', 31, 1, 0, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (40, 'Rubia', 29, 2, 18, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (41, 'Alexa', 12, 3, 18, 5.2);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (42, 'Vinilo', 41, 3, 30, 5.5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (43, 'Finca', 26, 3, 50, 6);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (44, 'Más Música Local', 19, 3, 80, 8);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (45, 'Happy Ayu', 31, 10, 70, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (46, 'Happy Tucán', 27, 10, 25, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (47, 'Happy Nebbi', 33, 10, 50, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (48, 'Happy Colibrí', 17, 10, 30, 7);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (49, 'Happy Pava', 33, 10, 60, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (50, 'Happy Garceta', 28, 10, 30, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (51, 'Happy Trepadora', 16, 10, 30, 4.3);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (52, 'Eclipse', 45, 5, 0, 5.5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (53, 'Salazar', 17, 5, 0, 6);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (54, 'Golden', 21, 4, 0, 4.5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (55, 'Porter', 34, 4, 0, 5.5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (56, 'Roja', 27, 4, 0, 3.5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (57, 'Colaa', 1, 6, 0, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (58, 'Cols', 40, 6, 0, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (59, 'Colpa', 31, 6, 0, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (60, 'Neipa', 30, 6, 0, 7);
