INSERT INTO cervecerias (id, nombre, ubicacion_id, sitio_web, instagram) VALUES (1, 'Fierabrás', 4, 'https://www.cervezafierabras.com/', 'cervezafierabras');
INSERT INTO cervecerias (id, nombre, ubicacion_id, sitio_web, instagram) VALUES (2, 'BBC', 14, 'https://www.bbccerveceria.com/', 'bbccerveceria');
INSERT INTO cervecerias (id, nombre, ubicacion_id, sitio_web, instagram) VALUES (3, 'Cervezas Kalima', 31, 'https://www.cervezaskalima.com/', 'cervezaskalima');
INSERT INTO cervecerias (id, nombre, ubicacion_id, sitio_web, instagram) VALUES (4, 'Cervecería Cartagena', 5, 'https://cerveceriacartagena.co/', 'ctgcraftbeer');
INSERT INTO cervecerias (id, nombre, ubicacion_id, sitio_web, instagram) VALUES (5, 'Bari Cerveza Artesanal', 23, 'https://www.cervezabari.com/', 'cervezabari');
INSERT INTO cervecerias (id, nombre, ubicacion_id, sitio_web, instagram) VALUES (6, 'Lino Brewing Company', 15, 'https://linktr.ee/Linobrewing', 'lino_brewing');
INSERT INTO cervecerias (id, nombre, ubicacion_id, sitio_web, instagram) VALUES (7, '20 Mission', 2, 'https://20missioncerveza.com/', '20missioncerveza');
INSERT INTO cervecerias (id, nombre, ubicacion_id, sitio_web, instagram) VALUES (8, '3 Cordilleras', 2, 'https://3cordilleras.com/', '3cordilleras');
INSERT INTO cervecerias (id, nombre, ubicacion_id, sitio_web, instagram) VALUES (9, 'Rincón del Mar', 2, 'https://rincondelmar.com.co/', 'rincondelmarcerveceria');
INSERT INTO cervecerias (id, nombre, ubicacion_id, sitio_web, instagram) VALUES (10, 'Nevada Cerveceria', 20, 'https://nevadacerveceria.beer', 'nevadacerveceria');
INSERT INTO cervecerias (id, nombre, ubicacion_id, sitio_web, instagram) VALUES (11, 'Bruder', 6, 'https://www.bruder.com.co/', 'bruder_cerveza');
