INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (1, 'Blanca', 43, 2, 15, 4.6);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (2, 'Mona', 12, 2, 20, 3.9);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (3, 'Mulata', 1, 2, 27, 5.2);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (4, 'Mestiza', 4, 2, 29, 4.8);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (5, 'Negra', 41, 2, 25, 6.4);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (6, 'Rose', 34, 2, 15, 3.8);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (7, 'Blonde', 12, 1, 19, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (8, 'Witbier', 44, 1, 16, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (9, 'Pale Ale', 30, 1, 30, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (10, 'Porter', 33, 1, 30, 5.5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (11, 'IPA', 26, 1, 60, 6);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (12, 'Saison', 35, 1, 27, 6);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (13, 'Açaí', 27, 3, 0, 6.7);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (14, 'Cacao', 27, 3, 0, 6.2);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (15, 'Canábica', 27, 3, 0, 6.7);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (16, 'Colorada', 27, 3, 0, 5.5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (17, 'Coca', 4, 3, 0, 6.2);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (18, 'Gringa', 4, 3, 0, 6.3);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (19, 'IPA Maracuyá', 26, 6, 45, 6.5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (20, 'Barley Wine', 13, 6, 45, 12);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (21, 'Dog Lover', 42, 6, 32, 4.5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (22, 'Café', 36, 6, 30, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (23, 'Pueblito', 31, 6, 25, 4.5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (24, 'Maracuyá', 7, 6, 23, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (25, 'Roja', 42, 6, 32, 4.5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (26, 'Chocolate', 15, 6, 38, 8.5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (27, 'Rubia', 31, 6, 25, 4.5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (28, 'Imperial Strout', 25, 6, 40, 8.5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (29, 'Septimazo', 26, 4, 83, 6);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (30, 'Macondo', 39, 4, 37, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (31, 'Monserrate', 11, 4, 37, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (32, 'Lager', 29, 4, 18, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (33, 'Bacatá', 44, 4, 14, 4.1);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (34, 'Chapinero', 33, 4, 35, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (35, 'Cajicá', 24, 4, 16, 5.3);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (36, 'Isabel la Católica', 12, 5, 0, 4.8);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (37, 'Dulcinea', 14, 5, 0, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (38, 'Juana de Arco', 33, 5, 0, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (39, 'Maria Antonieta', 30, 5, 0, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (40, 'Rubia', 29, 4, 18, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (41, 'Alexa', 12, 7, 18, 5.2);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (42, 'Vinilo', 40, 7, 30, 5.5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (43, 'Finca', 26, 7, 50, 6);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (44, 'Más Música Local', 19, 7, 80, 8);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (45, 'Happy Ayu', 30, 8, 70, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (46, 'Happy Tucán', 27, 8, 25, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (47, 'Happy Nebbi', 32, 8, 50, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (48, 'Happy Colibrí', 17, 8, 30, 7);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (49, 'Happy Pava', 32, 8, 60, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (50, 'Happy Garceta', 28, 8, 30, 5);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (51, 'Happy Trepadora', 16, 8, 30, 4.3);
INSERT INTO cervezas (id, nombre, estilo_id, cerveceria_id, ibu, abv) VALUES (52, 'Eclipse', 44, 9, 0, 5.5);
