INSERT INTO estilos (id, nombre) VALUES (1, 'Amber Ale');
INSERT INTO estilos (id, nombre) VALUES (2, 'American Amber Ale');
INSERT INTO estilos (id, nombre) VALUES (3, 'American Blonde Ale');
INSERT INTO estilos (id, nombre) VALUES (4, 'American Pale Ale');
INSERT INTO estilos (id, nombre) VALUES (5, 'American Wheat Ale');
INSERT INTO estilos (id, nombre) VALUES (6, 'Barleywine');
INSERT INTO estilos (id, nombre) VALUES (7, 'Belgian Ale');
INSERT INTO estilos (id, nombre) VALUES (8, 'Belgian Dubbel');
INSERT INTO estilos (id, nombre) VALUES (9, 'Belgian Quadrupel');
INSERT INTO estilos (id, nombre) VALUES (10, 'Belgian Tripel');
INSERT INTO estilos (id, nombre) VALUES (11, 'Bitter');
INSERT INTO estilos (id, nombre) VALUES (12, 'Blonde Ale');
INSERT INTO estilos (id, nombre) VALUES (13, 'British Ale');
INSERT INTO estilos (id, nombre) VALUES (14, 'Brown Ale');
INSERT INTO estilos (id, nombre) VALUES (15, 'Chocolate Stout');
INSERT INTO estilos (id, nombre) VALUES (16, 'Citra IPA');
INSERT INTO estilos (id, nombre) VALUES (17, 'Coffee Stout');
INSERT INTO estilos (id, nombre) VALUES (18, 'Cream Ale');
INSERT INTO estilos (id, nombre) VALUES (19, 'Double IPA');
INSERT INTO estilos (id, nombre) VALUES (20, 'Fruit Beer');
INSERT INTO estilos (id, nombre) VALUES (21, 'Golden Ale');
INSERT INTO estilos (id, nombre) VALUES (22, 'Gose');
INSERT INTO estilos (id, nombre) VALUES (23, 'Hefeweizen');
INSERT INTO estilos (id, nombre) VALUES (24, 'Honey Ale');
INSERT INTO estilos (id, nombre) VALUES (25, 'Imperial Strout');
INSERT INTO estilos (id, nombre) VALUES (26, 'India Pale Ale (IPA)');
INSERT INTO estilos (id, nombre) VALUES (27, 'Irish Red Ale');
INSERT INTO estilos (id, nombre) VALUES (28, 'Kolsch');
INSERT INTO estilos (id, nombre) VALUES (29, 'Lager');
INSERT INTO estilos (id, nombre) VALUES (30, 'Pale Ale');
INSERT INTO estilos (id, nombre) VALUES (31, 'Pilsen Lager');
INSERT INTO estilos (id, nombre) VALUES (32, 'Pilsner');
INSERT INTO estilos (id, nombre) VALUES (33, 'Porter');
INSERT INTO estilos (id, nombre) VALUES (34, 'Rose');
INSERT INTO estilos (id, nombre) VALUES (35, 'Saison');
INSERT INTO estilos (id, nombre) VALUES (36, 'Schwartzbier');
INSERT INTO estilos (id, nombre) VALUES (37, 'Scotch Ale');
INSERT INTO estilos (id, nombre) VALUES (38, 'Sour Ale');
INSERT INTO estilos (id, nombre) VALUES (39, 'Stout');
INSERT INTO estilos (id, nombre) VALUES (40, 'Stout Ale');
INSERT INTO estilos (id, nombre) VALUES (41, 'Sweet Stout');
INSERT INTO estilos (id, nombre) VALUES (42, 'Vienna Lager');
INSERT INTO estilos (id, nombre) VALUES (43, 'Wheat Ale');
INSERT INTO estilos (id, nombre) VALUES (44, 'Witbier');
