INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (1, 'Agua de Manantial', 1);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (2, 'Cannabis', 8);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (3, 'Coca', 8);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (4, 'Amber Malt', 4);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (5, 'Belgian Special', 4);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (6, 'Biscuit Malt', 4);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (7, 'Black Barley', 4);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (8, 'Black Patent', 4);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (9, 'Brown Malt', 4);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (10, 'CaraVienne', 4);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (11, 'Carafa Special', 4);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (12, 'Caramel Malt', 4);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (13, 'Carapils', 4);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (14, 'Chocolate Malt', 4);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (15, 'Honey Malt', 4);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (16, 'Munich Malt', 4);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (17, 'Pale Malt', 4);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (18, 'Peated Malt', 4);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (19, 'Roasted Barley', 4);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (20, 'Rye Malt', 4);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (21, 'Special Roast', 4);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (22, 'Victory Malt', 4);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (23, 'Vienna Malt', 4);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (24, 'Wheat Malt', 4);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (25, 'Wiener', 4);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (26, 'Açaí', 7);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (27, 'Cacao', 7);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (28, 'Café', 7);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (29, 'Ciruela', 7);
INSERT INTO ingredientes (id, nombre, tipo_ingrediente_id) VALUES (30, 'Maracuyá', 7);
