CREATE TABLE "ubicaciones" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "municipio" varchar,
  "departamento" varchar
);

CREATE TABLE "cervecerias" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "ubicacion_id" int,
  "sitio_web" varchar,
  "instagram" varchar
);

CREATE TABLE "estilos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar
);

CREATE TABLE "rangosAbv" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "valor_inicial" float,
  "valor_final" float
);

CREATE TABLE "rangosIbu" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "valor_inicial" float,
  "valor_final" float
);

CREATE TABLE "cervezas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "cerveceria_id" int,
  "estilo_id" int,
  "ibu" float,
  "abv" float
);

CREATE TABLE "tipos_ingredientes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar
);

CREATE TABLE "ingredientes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo_ingrediente_id" int,
  "nombre" varchar
);

CREATE TABLE "ingredientes_cervezas" (
  "cerveza_id" int,
  "ingrediente_id" int,
  PRIMARY KEY ("cerveza_id", "ingrediente_id")
);

CREATE TABLE "unidades_volumen" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "abreviatura" varchar
);

CREATE TABLE "envasados" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar
);

CREATE TABLE "envasados_cervezas" (
  "cerveza_id" int,
  "envasado_id" int,
  "unidad_volumen_id" int,
  "volumen" int
);

ALTER TABLE "cervecerias" ADD FOREIGN KEY ("ubicacion_id") REFERENCES "ubicaciones" ("id");

ALTER TABLE "cervezas" ADD FOREIGN KEY ("cerveceria_id") REFERENCES "cervecerias" ("id");

ALTER TABLE "cervezas" ADD FOREIGN KEY ("estilo_id") REFERENCES "estilos" ("id");

ALTER TABLE "ingredientes" ADD FOREIGN KEY ("tipo_ingrediente_id") REFERENCES "tipos_ingredientes" ("id");

ALTER TABLE "ingredientes_cervezas" ADD FOREIGN KEY ("cerveza_id") REFERENCES "cervezas" ("id");

ALTER TABLE "ingredientes_cervezas" ADD FOREIGN KEY ("ingrediente_id") REFERENCES "ingredientes" ("id");

ALTER TABLE "envasados_cervezas" ADD FOREIGN KEY ("unidad_volumen_id") REFERENCES "unidades_volumen" ("id");

ALTER TABLE "envasados_cervezas" ADD FOREIGN KEY ("cerveza_id") REFERENCES "cervezas" ("id");

ALTER TABLE "envasados_cervezas" ADD FOREIGN KEY ("envasado_id") REFERENCES "envasados" ("id");
