//Cervezas Artesanales Colombia

table ubicaciones{
  id int [pk, increment]
  municipio varchar
  departamento varchar
}

table cervecerias {
  id int [pk, increment]
  nombre varchar
  ubicacion_id int
  sitio_web varchar
  instagram varchar
}

Ref:ubicaciones.id < cervecerias.ubicacion_id

table estilos {
  id int [pk, increment]
  nombre varchar
}

table rangosAbv {
  id int [pk, increment]
  nombre varchar
  valor_inicial float
  valor_final float
}

table rangosIbu {
  id int [pk, increment]
  nombre varchar
  valor_inicial float
  valor_final float
}

table cervezas {
  id int [pk, increment]
  nombre varchar
  cerveceria_id int
  estilo_id int
  ibu float
  abv float
}
Ref:cervecerias.id < cervezas.cerveceria_id
Ref:estilos.id < cervezas.estilo_id


table tipos_ingredientes {
  id int [pk, increment]
  nombre varchar
}

table ingredientes {
  id int [pk, increment]
  tipo_ingrediente_id int
  nombre varchar
}

Ref:tipos_ingredientes.id < ingredientes.tipo_ingrediente_id

table ingredientes_cervezas {
  cerveza_id int
  ingrediente_id int

  Indexes {
    (cerveza_id, ingrediente_id) [pk]
  }
}

Ref:cervezas.id < ingredientes_cervezas.cerveza_id
Ref:ingredientes.id < ingredientes_cervezas.ingrediente_id

table unidades_volumen {
  id int [pk, increment]
  nombre varchar
  abreviatura varchar  
}

table envasados {
  id int [pk, increment]
  nombre varchar
}

table envasados_cervezas {
  cerveza_id int
  envasado_id int
  unidad_volumen_id int
  volumen int
}

Ref:unidades_volumen.id < envasados_cervezas.unidad_volumen_id
Ref:cervezas.id < envasados_cervezas.cerveza_id
Ref:envasados.id < envasados_cervezas.envasado_id
